'use client'

import { useState, useEffect } from 'react'
import { ArrowRight, ChevronDown, Menu, X, Activity, Bluetooth, ShieldCheck, Database, Fingerprint, Wifi, Check, Play, Minus } from 'lucide-react'

function TypingHeading({ text, className = '' }: { text: string; className?: string }) {
  const [displayText, setDisplayText] = useState('')
  const [showCursor, setShowCursor] = useState(true)

  useEffect(() => {
    let index = 0
    const interval = setInterval(() => {
      if (index < text.length) {
        setDisplayText(text.slice(0, index + 1))
        index++
      } else {
        clearInterval(interval)
        setTimeout(() => setShowCursor(false), 1000)
      }
    }, 50)
    return () => clearInterval(interval)
  }, [text])

  return <span className={className}>{displayText}{showCursor && <span className="typing-cursor">|</span>}</span>
}

const navItems = [['Technology', '#technology'], ['IP-10 Monitor', '#ip10'], ['How It Works', '#how-it-works'], ['Easy to Use', '#easy-use'], ['Platform', '#platform'], ['About Us', '#about']]
const steps = ['Sample Applied', 'Plasma Separation', 'Immuno Reaction', 'Electrochemical Detection', 'Result Displayed']
const stepDescriptions = ['20 µL fingerstick blood sample is applied to the disposable cartridge inlet.', 'Plasma separates from whole blood through the integrated plasma separation membrane.', 'IP-10 biomarker binds to capture and detection antibodies in the reaction zone.', 'Electrochemical signal is generated by redox substrate and measured in the detection zone.', 'IP-10 level and therapy response are displayed on the device screen in a few minutes.']

function IP10Monitor({ flat = false }: { flat?: boolean }) {
  return (
    <div className={`ip10-device ${flat ? 'ip10-device-flat' : ''}`} aria-label="IP-10 TB Therapy Monitor with scrollable patient monitoring screen">
      <div className="ip10-shell">
        <div className="ip10-screen-wrap">
          <div className="ip10-screen">
            <div className="screen-top"><span>IP-10</span><span className="screen-live">● LIVE</span></div>
            <div className="screen-scroll" tabIndex={0} aria-label="Scrollable patient monitoring results">
              <section className="screen-section"><span className="screen-label">LATEST IP-10 LEVEL</span><strong className="screen-value">356 <small>pg/mL</small></strong><div className="screen-meta"><span>Patient ID <b>10293</b></span><span>15 JUN 2024</span></div><div className="screen-divider" /><span className="screen-label">THERAPY PROGRESS</span><strong className="screen-progress">↓ 48%</strong><span className="screen-response">GOOD RESPONSE</span><div className="screen-panel"><span>Next measurement</span><b>In 7 days</b></div></section>
              <section className="screen-section"><span className="screen-label">PATIENT TREND</span><strong className="screen-value">680 → 356 <small>pg/mL</small></strong><div className="screen-chart"><i /><i /><i /><i /><i /><i /></div><div className="screen-panel"><span>Baseline</span><b>680 pg/mL</b></div><div className="screen-panel"><span>Latest result</span><b className="screen-green">Good response</b></div></section>
              <section className="screen-section"><span className="screen-label">CARE PLAN</span><div className="screen-panel"><span>Current therapy</span><b>Week 04 / 06</b></div><div className="screen-panel"><span>Review status</span><b className="screen-green">On track</b></div><span className="screen-hint">Swipe or scroll for more</span></section>
            </div>
          </div>
        </div>
        <div className="ip10-button"><span /></div><div className="ip10-port" />
      </div>
      <div className="ip10-shadow" />
    </div>
  )
}

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  return (
    <main className="site-shell">
      <header className="nav-wrap">
        <nav className="nav container" aria-label="Main navigation">
          <a className="wordmark" href="#top"><img src="/logo.png" alt="MRX Health Tech" className="logo-image" /></a>
          <div className={`nav-links ${menuOpen ? 'open' : ''}`}>
            {navItems.map(([label, href]) => <a key={label} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}
            <a className="mobile-cta" href="#contact">Request a Demo <ArrowRight size={15} /></a>
          </div>
          <div className="nav-actions"><a href="#contact" className="button button-small">Request a Demo <ArrowRight size={15} /></a></div>
          <button className="menu-button" aria-label={menuOpen ? 'Close menu' : 'Open menu'} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
        </nav>
      </header>

      <section className="hero" id="top">
        <div className="hero-glow" />
        <div className="container hero-grid">
          <div className="hero-copy reveal">
            <div className="eyebrow"><span className="eyebrow-dot" /> Because every breath deserves a tomorrow</div>
            <h1><TypingHeading text="Smarter TB monitoring." /><br /><em>Connected clinical insight.</em></h1>
            <p className="hero-lead"><TypingHeading text="Point-of-care biomarker monitoring designed for a more connected TB care journey." className="typing-text-sm" /></p>
            <p className="hero-body">MRX HealthTech combines point-of-care diagnostics, biomarker monitoring and connected digital workflows to help healthcare teams follow patient progress with greater clarity.</p>
            <div className="hero-actions"><a className="button" href="#contact">Request a Demo <ArrowRight size={17} /></a><a className="text-link" href="#ip10">Explore IP-10 <ArrowRight size={17} /></a></div>
            <div className="trust-line"><ShieldCheck size={17} /> Designed for connected, longitudinal patient monitoring</div>
          </div>
          <div className="hero-product hero-device-clean reveal reveal-delay">
            <IP10Monitor />
          </div>
        </div>
        <div className="scroll-cue"><span>SCROLL TO EXPLORE</span><ChevronDown size={16} /></div>
      </section>

      <section className="intro section" id="technology"><div className="container">
        <div className="section-kicker">THE MRX APPROACH <span /></div>
        <div className="intro-heading"><h2>Technology designed around <span>the patient journey.</span></h2><p>TB monitoring requires more than a single measurement. MRX HealthTech is building a connected platform that brings patient records, biomarker observations, follow-ups and point-of-care device data into one longitudinal view.</p></div>
        <div className="feature-grid">{[['01','Patient-Centered Monitoring','Maintain a structured longitudinal record across patient encounters and monitoring events.',Fingerprint],['02','Biomarker Intelligence','Capture and visualize time-stamped biomarker observations across the patient journey.',Activity],['03','Connected Diagnostics','Create a foundation for integrating MRX point-of-care devices with digital clinical workflows.',Wifi]].map(([n,title,desc,Icon]) => <article className="feature-card" key={title as string}><div className="feature-top"><span>{n}</span><Icon size={21} /></div><h3>{title as string}</h3><p>{desc as string}</p><a href="#platform">Learn more <ArrowRight size={15} /></a></article>)}</div>
      </div></section>

      <section className="product-section section" id="ip10"><div className="container product-grid">
        <div className="product-visual"><div className="visual-tag">01 <span>THE DEVICE</span></div><IP10Monitor flat /><div className="visual-caption"><span>IP-10</span><span>TB THERAPY MONITOR · TAP SCREEN TO EXPLORE</span></div></div>
        <div className="product-copy"><div className="section-kicker">IP-10 TB THERAPY MONITOR <span /></div><h2>Built for the<br /><span>point of care.</span></h2><p>Point-of-care inflammatory response monitoring in a compact handheld device. IP-10 brings a clear result workflow closer to the patient and into the connected monitoring journey.</p><div className="capability-list">{[['Portable','Compact handheld form factor'],['Point-of-care','Designed for monitoring workflows'],['Connected','A foundation for digital integration'],['Digital results','Clear result display']].map(([a,b]) => <div className="capability" key={a}><Check size={16} /><span><b>{a}</b>{b}</span></div>)}</div><a className="button button-light" href="#how-it-works">Explore the IP-10 <ArrowRight size={17} /></a></div>
      </div></section>

      <section className="workflow section" id="how-it-works"><div className="container"><div className="workflow-heading"><div><div className="section-kicker">THE WORKFLOW <span /></div><h2>From sample to<br /><span>connected insight.</span></h2></div><p>The IP-10 workflow connects a point-of-care sample with a digital clinical record—without presenting itself as an autonomous diagnostic or treatment engine.</p></div><div className="steps">{steps.map((step,i) => <div className="step" key={step}><div className="step-number">0{i+1}</div><div className="step-line" /><h3>{step}</h3><p>{stepDescriptions[i]}</p></div>)}</div></div></section>

      <section className="easy-use section" id="easy-use"><div className="container"><div className="center-heading"><div className="section-kicker">EASY TO USE <span /></div><h2>Results in<br /><span>few minutes.</span></h2></div><div className="easy-steps">{[['Finger Prick','Simple fingerstick blood collection using the included lancet'],['Apply Sample','Insert the disposable cartridge and apply 20 µL sample'],['Get Result','IP-10 level and therapy response displayed on screen']].map(([title,desc],i) => <div className="easy-step" key={title}><div className="easy-step-number">{i+1}</div><h3>{title}</h3><p>{desc}</p></div>)}</div></div></section>

      <section className="platform section" id="platform"><div className="container"><div className="platform-intro"><div><div className="section-kicker">THE CONNECTED PLATFORM <span /></div><h2>One connected view of<br /><span>the patient journey.</span></h2></div><p>MRX is designed to organize patient records, encounters, biomarker observations and follow-ups into a coherent longitudinal history.</p></div><div className="browser"><div className="browser-bar"><div className="browser-dots"><i /><i /><i /></div><span>app.mrxhealthtech.com / patient / 10293</span><ShieldCheck size={14} /></div><div className="browser-content"><aside><div className="mini-logo"><img src="/logo.png" alt="MRX" className="mini-logo-image" /></div><b>Patient overview</b><span>Patients</span><span>Biomarker trends</span><span>Follow-ups</span><span>Reports</span><div className="side-bottom"><span>Device status</span><strong><i /> Connected</strong></div></aside><div className="dash"><div className="dash-top"><div><small>MRX TB PATIENT MONITORING PLATFORM</small><h3>Patient ID: 10293</h3></div><span className="status-badge"><i /> Active monitoring</span></div><div className="metrics"><div><small>BASELINE</small><strong>680 <sup>pg/mL</sup></strong><span>Recorded 20 May 2024</span></div><div><small>LATEST BIOMARKER</small><strong>356 <sup>pg/mL</sup></strong><span className="green">↓ 48% from baseline</span></div><div><small>FOLLOW-UPS</small><strong>04</strong><span>Last updated 15 Jun 2024</span></div></div><div className="chart-card"><div className="chart-title"><b>Biomarker trend</b><span>Last 30 days <ChevronDown size={13} /></span></div><svg viewBox="0 0 600 150" role="img" aria-label="Illustrative biomarker trend chart"><path d="M0 35 C60 28 80 65 140 58 S210 48 255 92 S330 75 385 104 S470 92 520 128 S570 114 600 120" fill="none" stroke="#f45319" strokeWidth="3" /><path d="M0 35 C60 28 80 65 140 58 S210 48 255 92 S330 75 385 104 S470 92 520 128 S570 114 600 120 V150 H0Z" fill="url(#fade)" /><defs><linearGradient id="fade" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#f45319" stopOpacity=".17"/><stop offset="1" stopColor="#f45319" stopOpacity="0"/></linearGradient></defs></svg><div className="chart-labels"><span>20 May</span><span>27 May</span><span>03 Jun</span><span>10 Jun</span><span>15 Jun</span></div></div></div></div></div><div className="platform-footer"><span>Marketing preview — representative interface, not a clinical dashboard.</span><a href="#contact">Explore the MRX Platform <ArrowRight size={15} /></a></div></div></section>

      <section className="journey section"><div className="container journey-grid"><div><div className="section-kicker">LONGITUDINAL MONITORING <span /></div><h2>Monitor change<br /><span>over time.</span></h2><p>MRX is designed to organize time-stamped observations, encounters and follow-up records into a coherent longitudinal patient history.</p><div className="disclaimer"><ShieldCheck size={17} /> Recorded trends support clinical review and do not independently determine diagnosis or treatment.</div></div><div className="timeline"><div className="timeline-line" />{['Baseline','Follow-up','Biomarker observation','Review','Longitudinal history'].map((x,i) => <div className={`timeline-item ${i===4?'active':''}`} key={x}><span>{String(i+1).padStart(2,'0')}</span><b>{x}</b><small>{['Initial patient record','Encounter recorded','IP-10 result added','Clinical review point','Connected patient history'][i]}</small></div>)}</div></div></section>

      <section className="why section"><div className="container"><div className="center-heading"><div className="section-kicker">WHY MRX <span /></div><h2>Built for connected <span>healthcare.</span></h2></div><div className="why-grid">{[['01','Point-of-Care','Bring monitoring closer to the patient.',Activity],['02','Longitudinal Data','Keep patient observations organized over time.',Database],['03','Connected Devices','Create a foundation for MRX device integration.',Bluetooth],['04','Future Ready','Designed to support additional biomarkers and future analytics.',Play]].map(([n,t,d,I])=><div className="why-card" key={t as string}><span>{n}</span><I size={22}/><h3>{t as string}</h3><p>{d as string}</p></div>)}</div></div></section>

      <section className="roadmap section"><div className="container"><div className="center-heading"><div className="section-kicker light-kicker">THE ROAD AHEAD <span /></div><h2>Designed to evolve<br /><span>with healthcare.</span></h2><p>MRX is building a modular foundation for the future of connected monitoring.</p></div><div className="roadmap-grid">{[['TODAY','IP-10','Current biomarker monitoring'],['NEXT','+','Additional MRX biomarkers'],['CONNECTED','↔','Multiplex device integration'],['INTELLIGENCE','✦','Validated analytics & AI']].map(([a,b,c],i)=><div className="roadmap-item" key={a}><small>{a}</small><strong className={i===0?'orange':''}>{b}</strong><span>{c}</span>{i<3&&<ArrowRight className="road-arrow" size={20}/>}</div>)}</div><p className="roadmap-note">Future AI-assisted interpretation — subject to clinical validation, governance and regulatory requirements.</p></div></section>

      <section className="about section" id="about"><div className="container"><div className="center-heading"><div className="section-kicker">LEADERSHIP <span /></div><h2>Meet the <span>founders.</span></h2></div><div className="team-grid"><div className="team-card"><img src="/founder.jpg" alt="Mokshada Desale" className="team-photo" /><div className="team-info"><h3>Mokshada Desale</h3><p className="team-title">Founder & CEO | MRX HealthTECH</p><p className="team-desc">As Founder & CEO, Mokshada drives MRX HealthTECH's healthcare innovation and technology vision, bridging clinical needs with medical-device development and scalable healthcare solutions.</p><div className="team-focus"><span>MedTech Strategy</span><span>Medical Devices</span><span>Healthcare Innovation</span><span>Product Development</span></div></div></div><div className="team-card"><img src="/cofounder.jpg" alt="Dnyanesh Manoj Magare" className="team-photo" /><div className="team-info"><h3>Dnyanesh Manoj Magare</h3><p className="team-title">Co-Founder & MD | Tech Team Lead</p><p className="team-desc">As Co-Founder, MD, and Tech Team Lead at MRX HealthTech, Dnyanesh drives the company's technology vision and engineering operations.</p><div className="team-focus"><span>Tech Strategy</span><span>Cybersecurity</span><span>HealthTech Architecture</span></div><a href="mailto:dnyaneshmagare7@gmail.com" className="team-email">dnyaneshmagare7@gmail.com</a></div></div></div></div></section>

      <section className="cta" id="contact"><div className="cta-orb" /><div className="container cta-inner"><div><div className="section-kicker light-kicker">START A CONVERSATION <span /></div><h2>Let&apos;s build the future of<br /><span>connected patient monitoring.</span></h2><p>Explore how MRX HealthTech can support your clinical monitoring workflow.</p></div><div className="cta-actions"><a className="button button-white" href="mailto:hello@mrxhealthtech.com">Request a Demo <ArrowRight size={17} /></a><a className="cta-contact" href="mailto:hello@mrxhealthtech.com">Contact MRX <ArrowRight size={16} /></a></div></div></section>

      <footer className="footer"><div className="container footer-top"><a className="wordmark footer-mark" href="#top"><img src="/logo.png" alt="MRX Health Tech" className="logo-image" /></a><p>Connected technology for smarter patient monitoring.</p><div className="footer-links">{navItems.slice(0,5).map(([l,h])=><a key={l} href={h}>{l}</a>)}<a href="#about">About</a><a href="#contact">Contact</a></div></div><div className="container footer-bottom"><span>© 2026 MRX HealthTech. All rights reserved.</span><div><a href="#top">Privacy</a><a href="#top">Terms</a></div></div></footer>
    </main>
  )
}

const _unused = Minus
